---

{{- if .Values.knativeDeploy }}
{{- else }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-2
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: NodePort 
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30100
    protocol: TCP
    name: http
  selector:
    app: {{ template "fullname" . }}
{{- end }}
